## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 184003368@qq.com #发送邮件的邮箱地址
    password: tqmviliiupckcbcd
    #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 587
    from: 184003368@qq.com # 发送邮件的地址，和上面username一致
  jpa:
    show-sql: true
  datasource: #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-edu?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#验证码有效时间：毫秒单位 1000*60*10=10分钟
authcode:
  expire_time: 600000

#ip防爆刷配置：多少分钟内，请求限制多少
ip:
  minute: 1 #单位分钟
  max_req_num: 8

#暴露所有通信端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
